cargo-features = ["workspace-inheritance"]

[package]
name = "phoenix-sdk-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
solana-program = { workspace = true }
phoenix-types = { workspace = true }
borsh = { workspace = true }
solana-sdk = { workspace = true }
num-traits = "0.2"
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26"
itertools = "0.10.5"